import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/Color';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  invoiceContainer: {
    height: 250,
    width: '85%',
    backgroundColor: Colors.invoiceContainer,
    borderRadius: 5,
    shadowColor: Colors.shadowColor,
    shadowOffset: { width: 1, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    marginBottom: 20,
  },
  rowContainer: {
    padding: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceLabel: {
    fontSize: 16,
    fontWeight: '500',
  },
  priceText: {
    fontWeight: '600',
    fontSize: 16,
  },
  divider: {
    marginTop: 10,
    height: 1,
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.white,
  },
  finalAmountContainer: {
    padding: 9,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
    width: '100%',
    backgroundColor: '#cfb3b3',
    overflow: 'hidden',
  },
  formContainer: {
    marginTop: 15,
    width: '85%',
    marginBottom: 30,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: Colors.infoText,
    marginBottom: 20,
  },
  payButton: {
    backgroundColor: Colors.payButton,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
  },
  payButtonText: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: '600',
  },
  bookingSummaryContainer: {
    width: '100%',
    backgroundColor: Colors.white,
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    marginTop: 15,
    marginBottom: 10,
    elevation: 2,
    shadowColor: Colors.shadowColor,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.infoText,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderColor,
    paddingBottom: 6,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: Colors.label,
    fontWeight: '500',
  },
  summaryValue: {
    fontSize: 14,
    color: Colors.infoText,
    fontWeight: '600',
    textAlign: 'right',
    flex: 1,
    marginLeft: 16,
  },
  seatsText: {
    color: Colors.seatsText,
  },
});
